dashpay/rs-tenderdash-abci

- abci/Cargo.toml
- abci/src/lib.rs
- abci/src/signatures.rs
- proto-compiler/src/functions.rs
- proto/Cargo.toml
- proto/src/error.rs
- proto/src/lib.rs
- proto/src/signatures.rs
> chore!: move signature functions to abci and more strict type controls

- abci/examples/echo_socket.rs
- abci/src/application.rs
- abci/src/server.rs
- abci/src/server/generic.rs
- abci/tests/kvstore.rs
- abci/tests/tcp.rs
- abci/tests/unix.rs
This reverts commit f9f4685ef6547a46d343633d5d6ce847c10e12f0.
> revert: "refactor: make self for offer_snapshot mutable (#27)"

- abci/Cargo.toml
- abci/src/application.rs
- abci/src/lib.rs
- abci/src/server/generic.rs
- abci/src/tracing_span.rs
- abci/tests/kvstore.rs
- proto-compiler/src/constants.rs
We need to log events with some predefined metadata, like height and round.
Implemented `tracing-span` feature that adds a span before each request is processed.
This feature is enabled by default.
The span includes:
* endpoint
* request_id
* height
* round
Started local devnet and investigated logs.
None
> feat(abci): support tracing::span inside rs-tenderdash-abci

- .github/actions/deps/action.yaml
- .github/workflows/rust-clippy.yml
sccache breaks github workflow runs.
Removed sccache
Passing tests
None
> ci: remove sccache from github actions

- Cargo.toml
- abci/src/lib.rs
- abci/src/server.rs
- abci/src/server/generic.rs
- proto/Cargo.toml
Build tenderdash-abci doesn't work reliably when switching various features on and off.
1. Added some conditional compilation clauses.
2. Fixed `prost` dependency of `tenderdash-proto` crate to include missing `prost-derive` feature, which is required
Try to build with various combinations of features.
None
> fix(tenderdash-abci): ensure crate features build without default features

- proto/build.rs
- proto/src/prelude.rs
We need a way to use custom revision of Tenderdash 
TENDERDASH_COMMITISH env var can now contain Tenderdash commit hash to use when fetching TD sources.
For example:
```
export TENDERDASH_COMMITISH=b1942323f5e6377014f7bb02f46879855307069b
cargo build
```
Locally 
None
> feat: use TENDERDASH_COMMITISH env var to set tenderdash rev to use

- proto-compiler/src/functions.rs
If download of tenderdash sources fail, it should be retried
Implemented retry mechanism
Locally + github actions
None
> build: retry download of tenderdash zip on unzip failures

- .github/actions/deps/action.yaml
- Dockerfile-alpine
- Dockerfile-debian
Tenderdash requires newer protoc version
Bumped protobuf version to 25.2
GHA
None
> build(deps): use protoc 25.2

- abci/Cargo.toml
- abci/src/server.rs
- abci/src/server/codec.rs
- abci/src/signatures.rs
- abci/tests/common/docker.rs
- abci/tests/kvstore.rs
- abci/tests/tcp.rs
- proto-compiler/Cargo.toml
- proto-compiler/src/functions.rs
- proto-compiler/src/lib.rs
- proto/Cargo.toml
- proto/build.rs
- proto/tests/unit.rs
Tenderdash 0.14 contains new vote extension type, **ThresholdRecoverRaw**.
* added support for ThresholdRecoverRaw 
* allow selecting Tenderdash commit from repo by setting TENDERDASH_COMMITISH env variable
* fixed tests
* fixed clippy warnings
* added support and tests for ThresholdRecoverRaw signatures
Added unit test
None
> feat!: support ThresholdRecoverRaw in tenderdash v0.14

- scripts/release.sh
When doing a release, we need to update version information
Added script that replaces versions in all relevant places
Locally
To be tested during release
None
> build: release script to update versions

- abci/src/application.rs
rs-tenderdash-abci should work correctly with tenderdash containing backwards-compatible abci changes
Changed version checks to ensure that new tenderdash with minor/patch abci version changes can be used
by older rs-tenderdash-abci.
GHA
None
> fix(abci): tenderdash version check requires exact version match

- proto-compiler/src/functions.rs
- proto-compiler/src/lib.rs
- proto/src/error.rs
- proto/src/lib.rs
- proto/src/serializers/part_set_header_total.rs
tenderdash-proto is rebuilt too often, as with every run it downloads new *.proto files and replaces old ones, affecting timestamps.
Added a state file that records last commitish. If it's the same as current one, proto files are not overwritten.
Locally + GHA, build tenderdash-abci a few times with `-vvv` and observing results.
None
> fix: tenderdash-proto rebuilt with every run due to changed *.proto

- proto-compiler/src/constants.rs
- proto/src/protobuf.rs
- proto/src/serializers/from_str.rs
- proto/src/serializers/time_duration.rs
- proto/src/serializers/timestamp.rs
- proto/tests/unit.rs
Consensus params serialized to JSON have different format than generated by Tenderdash.
Changed consensus params json verification to match Tenderdash format:
* quoted ints
* duration as nanoseconds
Unit test
Data format of some JSON messages was changed.
> fix(proto)!: wrong json serialization of consensus params

- abci/Cargo.toml
- proto-compiler/Cargo.toml
- proto/Cargo.toml
- proto/build.rs
New version of tenderdash published
Updated Tenderdash version to 0.14.0-dev.4
GHA
None
> build: release v0.14.0-dev.8 for tenderdash 0.14.0-dev.4

- abci/Cargo.toml
- proto-compiler/Cargo.toml
- proto-compiler/src/functions.rs
- proto-compiler/src/lib.rs
- proto/Cargo.toml
In some conditions, build of tenderdash-proto fails due to missing version/version.go. It is caused by lack of extracted tenderdash sources.
Re-download and re-extract tenderdash sources if the `proto` directory (which should be extracted from tenderdash sources) is not found.
Run `cargo build -p tenderdash-proto -vvv` a few times (but still needs more testing)
None
> fix(proto-compiler): existence of unzipped tenderdash sources not verified correctly

- abci/Cargo.toml
- abci/src/application.rs
- proto-compiler/Cargo.toml
- proto-compiler/src/constants.rs
- proto/Cargo.toml
- scripts/release.sh
We were getting some very incoherent logs that looked like:
```2024-03-20T17:57:29.133397Z TRACE                 main ThreadId(01) abci{endpoint="PrepareProposal" request_id="cf4cd98f-7b82-4abd-9a0e-8ba6e14a4f9e" height=242 round=0}: tenderdash_abci::application: sending ABCI response response=PrepareProposal(ResponsePrepareProposal { tx_records: [TxRecord { action: Unmodified, tx: [0, 0, 0, 55, 114, 93, 108, 17, 17, 56, 13, 209, 96, 40, 114, 236, 139, 226, 233, 33, 130, 102, 124, 23, 201, 218, 68, 243, 71, 25, 66, 46, 108, 18, 143, 0, 0, 0, 0, 0, 1, 0, 0, 1, 185, 56, 190, 248, 108, 141, 131, 219, 5, 227, 22, 201, 248, 210, 205, 195, 215, 32, 130, 212, 163, 192, 129, 100, 165, 136, 195, 43, 46, 157, 92, 196, 0, 30, 21, 115, 116, 114, 105, 110, 103, 32, 100, 111, 99, 95, 116, 121, 112, …
```
> refactor: improve debug logging of PrepareProposal and ProcessProposal

- .github/workflows/github-pages.yml
Generates Rust documentation and publishes it on Github Pages.
Github Actions code that publishes to the github pages - extracted from #16 
Go to https://dashpay.github.io/rs-tenderdash-abci/ and check the version is quite recent.
Inspect workflow run https://github.com/dashpay/rs-tenderdash-abci/actions/runs/8360268540/job/22885556331?pr=58
> build: deploy docs site on github pages

- abci/Cargo.toml
- abci/tests/kvstore.rs
- proto-compiler/Cargo.toml
- proto/Cargo.toml
- proto/build.rs
New Tenderdash 0.14.0-dev.5 released, with breaking changes in ABCI protocol
Update dependency
GHA
1. Added required ResponsePrepareProposal.app_version
2. Deprecated ConsensusParams.Version
> build: release 0.14.0-dev.11 for tenderdash v0.14.0-dev.5

- .github/workflows/test.yml
- proto-compiler/Cargo.toml
- proto-compiler/src/functions.rs
- proto-compiler/src/lib.rs
- proto/build.rs
- proto/src/.gitignore
- proto/src/lib.rs
When working with both no_std and std (grpc) features,  generated code is not always regenerated.
This can cause issues like including code requiring tonic in no_std mode.
Separated generated code into two modules: tenderdash_std and tenderdash_nostd, which are included/exported using conditional compilation.
Run cargo build with various combinations of features
None
> fix(proto-compiler): std and no-std generated code conflict

- abci/Cargo.toml
- proto-compiler/Cargo.toml
- proto/Cargo.toml
`default-features=false` on tenderdash-abci should imply `default-features=false` on tenderdash-proto, to build it in nostd mode.
Fixed features in tenderdash-abci
* added "std" feature that enables tenderdash-proto/std
* 
GHA
Built manually using a pet project.
none
> fix: nostd proto not propagated from tenderdash-abci

- abci/Cargo.toml
- proto-compiler/Cargo.toml
- proto-compiler/src/constants.rs
- proto-compiler/src/functions.rs
- proto-compiler/src/lib.rs
- proto/Cargo.toml
- proto/build.rs
- proto/src/.gitignore
- proto/src/error.rs
- proto/src/lib.rs
- proto/src/protobuf.rs
- proto/src/serializers/from_str.rs
- proto/src/serializers/part_set_header_total.rs
- proto/src/serializers/time_duration.rs
- proto/src/serializers/timestamp.rs
- proto/tests/unit.rs
After building it multiple times, tenderdash_nostd  sometimes refers to tonic which is unavailable due to changed features.
This impacts IDE which shows false errors, etc.
* deprecate "std" feature in favor of "grpc" feature ("std" is using tonic anyway)
* always build nostd, but don't re-export it in "grpc" mode
* in proto-compiler, build grpc based on func argument, not based on feature
* renamed module "tenderdash_std" to "tenderdash_grpc"
Run `cargo build --no-default-features` and `cargo build --no-default-features -F grpc` multiple times in various combinations to ensure it works
* "std" feature is deprecated but in backwards-compatible way
* renamed module `tendedash_proto::tenderdash_std` to `tendedash_proto::tenderdash_grpc`
> fix(proto-compiler): not used no-std proto definitions refer to tonic

- proto-compiler/src/constants.rs
- proto-compiler/src/functions.rs
- proto-compiler/src/lib.rs
In Ubuntu, protoc compiler is too old, and users don't know how to solve that
Added version detection
Modify `const DEP_PROTOC_VERSION` and run `cargo build -p tenderdash-proto` a few times.
None
> feat(proto-compiler): check required protoc version before build

- abci/Cargo.toml
- abci/tests/grpc.rs
- proto-compiler/Cargo.toml
- proto/Cargo.toml
- proto/build.rs
This is a first release candidate of Tenderdash
* Updated version
* Ignore grpc.rs::test_ipv6_server due to Tenderdash issue
GHA
None
> chore: release rs-tenderdash-abci v1.0.0-dev.1

- abci/Cargo.toml
- abci/tests/common/docker.rs
- abci/tests/grpc.rs
Cannot create new tokio runtime inside a runtime. This means that block_on() cannot be used.
Use tokio::spawn() together with pollster in tests to workaround the issue.
Run tests locally.
None
> test(abci): fix tokio spawning in grpc test

- abci/Cargo.toml
- proto-compiler/Cargo.toml
- proto/Cargo.toml
- proto/build.rs
- scripts/release.sh
Tenderdash 1.0.0 was released
* Bump version to 1.0.0
* Update Tenderdash dependency to 1.0.0
* Fix release script to use `tag` when fixing dashpay/platform dependency
GHA
None
> chore: release rs-tenderdash-abci 1.0.0 for tenderdash 1.0.0

- proto-compiler/Cargo.toml
- proto/Cargo.toml
* very old version of zip crate in use by proto-compiler
* unused prost_types in use by proto
update zip t 2.1.3, remove prost_types
GHA
```
cargo check --no-default-features
cargo check --no-default-features -F grpc
cargo check --no-default-features -F std
```
None
> build(proto): update zip and remove unused prost_type dep

- abci/Cargo.toml
- proto-compiler/Cargo.toml
- proto/Cargo.toml
- proto/build.rs
Update for new version of Tenderdash ABCI protocol (1.1.0), introduced in Tenderdash 1.1.0-dev.3
* update version to 1.1.0-dev.1
* use tenderdash 1.1.0-dev.3 as source of protobuf definitions and test images
GH Actions
Requires ABCI version 1.1.0+
> chore: release rs-tenderdash-abci 1.1.0-dev.1 for TD 1.1.0-dev.3+

- .github/workflows/test.yml
- proto-compiler/src/constants.rs
- proto/build.rs
- proto/tests/unit.rs
Tenderdash 1.3 includes new .tendermint.types.VersionParams.consensus_version field, and ABCI version 1.2.0.
* Bumped Tenderdash to 1.3.
* Added new field `consensus_version` as quoted.
* Improved release script and docs.
Integrated into Dash Platform.
None
> feat: support ConsensusParams.VersionParams.consensus_version from Tenderdash 1.3

- .github/workflows/test.yml
- README.md
- abci/Cargo.toml
- abci/README.md
- proto-compiler/Cargo.toml
- proto-compiler/src/constants.rs
- proto/Cargo.toml
- proto/build.rs
- proto/tests/unit.rs
- scripts/release.sh
New release
* Changed versioning - now we add minimum tenderdash version after `+` to rs-tenderdash-abci version
* Bump versions
* Improve release script
Integrated into Dash Platform
None
> build: release v1.2.0 for tenderdash 1.3.0
